package moshi.blossom.util.network;

/**
 * Enum representing different Minecraft packet types with their display names
 */
public enum Packets {
    // Client-bound packets
    UNKNOWN("Unknown"),
    C_CLICK_WINDOW("Click Window"),
    C_CLOSE_WINDOW("Close Window"),
    C_CUSTOM_PAYLOAD("Custom Payload"),
    C_CONFIRM_TRANSACTION("Confirm Transaction"),
    C_USE_ENTITY("Use Entity"),
    C_ENTITY_ACTION("Entity Action"),
    C_PLAYER_DIGGING("Player Digging"),
    C_RESOURCE_PACK_STATUS("Resource Pack Status"),
    C_PLAYER_ABILITIES("Player Abilities"),
    C_HELD_ITEM_CHANGE("Held Item Change"),
    C_TAB_COMPLETE("Tab Complete"),
    C_PLAYER("Player Movement"),
    C_INPUT("Input"),
    C_CLIENT_SETTINGS("Client Settings"),
    C_SPECTATE("Spectate"),
    C_CREATIVE_INVENTORY_ACTION("Creative Inventory Action"),
    C_ENCHANT_ITEM("Enchant Item"),
    C_PLAYER_BLOCK_PLACEMENT("Player Block Placement"),
    C_KEEP_ALIVE("Keep Alive"),
    C_CHAT_MESSAGE("Chat Message"),
    C_CLIENT_STATUS("Client Status"),
    C_ANIMATION("Animation"),
    C_UPDATE_SIGN("Update Sign"),

    // Server-bound packets
    S_WINDOW_PROPERTY("Window Property"),
    S_ENTITY_PROPERTIES("Entity Properties"),
    S_UPDATE_HEALTH("Update Health"),
    S_PLAYER_POS_LOOK("Player Position Look"),
    S_CHANGE_GAME_STATE("Change Game State"),
    S_WORLD_BORDER("World Border"),
    S_DISCONNECT("Disconnect"),
    S_UPDATE_SIGN("Update Sign"),
    S_EXPLOSION("Explosion"),
    S_UPDATE_SCORE("Update Score"),
    S_ENTITY_EFFECT("Entity Effect"),
    S_RESOURCE_PACK_SEND("Resource Pack Send"),
    S_SOUND_EFFECT("Sound Effect"),
    S_MAPS("Maps"),
    S_TEAMS("Teams"),
    S_OPEN_WINDOW("Open Window"),
    S_SPAWN_EXPERIENCE_ORB("Spawn Experience Orb"),
    S_COLLECT_ITEM("Collect Item"),
    S_BLOCK_ACTION("Block Action"),
    S_SET_EXPERIENCE("Set Experience"),
    S_ENTITY_EQUIPMENT("Entity Equipment"),
    S_HELD_ITEM_CHANGE("Held Item Change"),
    S_CHAT("Chat"),
    S_SPAWN_PLAYER("Spawn Player"),
    S_ENTITY_METADATA("Entity Metadata"),
    S_CLOSE_WINDOW("Close Window"),
    S_PLAYER_LIST_HEADER_FOOTER("Player List Header Footer"),
    S_SPAWN_POSITION("Spawn Position"),
    S_SPAWN_OBJECT("Spawn Object"),
    S_PLAYER_LIST_ITEM("Player List Item"),
    S_COMBAT_EVENT("Combat Event"),
    S_EFFECT("Effect"),
    S_DISPLAY_SCOREBOARD("Display Scoreboard"),
    S_PLAYER_ABILITIES("Player Abilities"),
    S_ENTITY_VELOCITY("Entity Velocity"),
    S_ENTITY_TELEPORT("Entity Teleport"),
    S_ENTITY("Entity"),
    S_BLOCK_BREAK_ANIM("Block Break Animation"),
    S_SET_SLOT("Set Slot"),
    S_ENTITY_ATTACH("Entity Attach"),
    S_ENTITY_HEAD_LOOK("Entity Head Look"),
    S_SIGN_EDITOR_OPEN("Sign Editor Open"),
    S_TITLE("Title"),
    S_SPAWN_MOB("Spawn Mob"),
    S_PARTICLES("Particles"),
    S_UPDATE_ENTITY_NBT("Update Entity NBT"),
    S_MAP_CHUNK_BULK("Map Chunk Bulk"),
    S_SPAWN_PAINTING("Spawn Painting"),
    S_SPAWN_GLOBAL_ENTITY("Spawn Global Entity"),
    S_ENTITY_STATUS("Entity Status"),
    S_CHUNK_DATA("Chunk Data"),
    S_TAB_COMPLETE("Tab Complete"),
    S_SERVER_DIFFICULTY("Server Difficulty"),
    S_DESTROY_ENTITIES("Destroy Entities"),
    S_WINDOW_ITEMS("Window Items"),
    S_JOIN_GAME("Join Game"),
    S_REMOVE_ENTITY_EFFECT("Remove Entity Effect"),
    S_CAMERA("Camera"),
    S_TIME_UPDATE("Time Update"),
    S_ANIMATION("Animation"),
    S_CUSTOM_PAYLOAD("Custom Payload"),
    S_STATISTICS("Statistics"),
    S_KEEP_ALIVE("Keep Alive"),
    S_UPDATE_TILE_ENTITY("Update Tile Entity"),
    S_USE_BED("Use Bed"),
    S_BLOCK_CHANGE("Block Change"),
    S_SET_COMPRESSION_LEVEL("Set Compression Level"),
    S_CONFIRM_TRANSACTION("Confirm Transaction"),
    S_MULTI_BLOCK_CHANGE("Multi Block Change"),
    S_RESPAWN("Respawn"),
    S_SCOREBOARD_OBJECTIVE("Scoreboard Objective");

    public final String displayName;

    Packets(String displayName) {
        this.displayName = displayName;
    }
}